services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Belsignum\ViteCritical\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  Belsignum\ViteCritical\Command\GetSlugsCommand:
    tags:
      - name: 'console.command'
        command: 'vite_critical:get-slugs'
        schedulable: false
